// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iesrzrseforfqbvyhvsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllc3J6cnNlZm9yZnFidnlodnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5NDY4ODIsImV4cCI6MjA4NTUyMjg4Mn0.G_d4saqB6fSl7f2sNpk79dFNJSOvbhvEOX6GPHjyzWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});